# Generated by Django 4.2.4 on 2023-08-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='id_user',
            new_name='id_user',
        ),
        migrations.AddField(
            model_name='newuser',
            name='last_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
