# Generated by Django 4.2.4 on 2023-08-30 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_id_username_newuser_id_user_newuser_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='id_user',
            new_name='id',
        ),
    ]
