# Generated by Django 4.2.4 on 2023-08-19 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id_especie', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name_especie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='petSize',
            fields=[
                ('id_pet_size', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name_tamano', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id_raza', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name_raza', models.CharField(max_length=100)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.especie')),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id_pet', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name_pet', models.CharField(max_length=100)),
                ('birth_date_pet', models.DateField()),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.raza')),
            ],
        ),
    ]
