# Generated by Django 4.2.4 on 2023-08-19 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_raza_pets_raza_id_pets_pet_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.owner'),
            preserve_default=False,
        ),
    ]
